# Generated by Django 3.0.6 on 2020-06-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Surgical'), (1, 'PPE'), (1, 'Syringes'), (1, 'Miscellaneous')])),
                ('flagged', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supply')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Volunteer')),
            ],
        ),
    ]
