# Generated by Django 3.0.6 on 2020-06-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200630_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
