# Generated by Django 3.0.6 on 2020-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
