# Generated by Django 3.0.6 on 2020-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200707_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
