# Generated by Django 3.0.6 on 2020-06-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200630_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Event'),
            preserve_default=False,
        ),
    ]
