# Generated by Django 3.0.6 on 2020-06-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_volunteer_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='login.Organization'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.Organization'),
        ),
    ]
