# Generated by Django 3.0.6 on 2020-07-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200701_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
