# Generated by Django 3.0.6 on 2020-07-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200701_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event',
        ),
        migrations.AddField(
            model_name='organization',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Organization'),
        ),
    ]
